name: Build Windows NSIS Installer

on:
  workflow_dispatch:

jobs:
  build:
    name: Build (Windows NSIS)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      # pnpm cache enabled in setup-node step above

      - name: Validate version consistency (pkg/tauri/cargo)
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            const tauri = JSON.parse(fs.readFileSync('src-tauri/tauri.conf.json', 'utf8'));
            const cargoToml = fs.readFileSync('src-tauri/Cargo.toml', 'utf8');
            const cargoVersion = (cargoToml.match(/^version\s*=\s*"([^"]+)"/m) || [null, null])[1];

            const mismatches = [];
            if (!pkg.version) mismatches.push('package.json missing version');
            if (!tauri.version) mismatches.push('tauri.conf.json missing version');
            if (!cargoVersion) mismatches.push('Cargo.toml missing version');

            if (pkg.version && tauri.version && pkg.version !== tauri.version) {
              mismatches.push(`package.json (${pkg.version}) != tauri.conf.json (${tauri.version})`);
            }
            if (pkg.version && cargoVersion && pkg.version !== cargoVersion) {
              mismatches.push(`package.json (${pkg.version}) != Cargo.toml (${cargoVersion})`);
            }

            if (mismatches.length) {
              core.setFailed('Version mismatch: ' + mismatches.join('; '));
            } else {
              core.info(`Version OK: ${pkg.version}`);
            }

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app with Tauri (NSIS only)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm tauri

      - name: Upload NSIS installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Focalite-Windows-NSIS
          path: src-tauri/target/release/bundle/nsis/*.exe
