name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Release build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest
          # Uncomment to build Linux assets as well
          # - os: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Enable pnpm cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and publish release artifacts
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm tauri
          # Attach artifacts to the tag's release
          tagName: ${{ github.ref_name }}
          releaseName: Focalite ${{ github.ref_name }}
          releaseBody: |
            Automated release for ${{ github.ref_name }}.
            - Built via GitHub Actions matrix (Windows/macOS).
            - Includes MSI/NSIS on Windows and DMG on macOS.
          draft: false
          prerelease: false

